# generated by datamodel-codegen:
#   filename:  mode.json
#   timestamp: 2025-03-18T10:43:28+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Model(BaseModel):
    __root__: Any
